### ISSUE TITLE
Create Alias GUI & Password Encryption

### ISSUE THREAD

**Issue by GQ722** [rsanchez-wsu/sp16-ceg3120#10]
I've implemented a simple GUI based on our first milestone. It is a 'Create / Edit Alias Window' that we described in class. I think the next step is to make the 'Save' button work. It would make connection to the database based on the user's username and password using the provided driver and URL.

https://github.com/rsanchez-wsu/sp16-ceg3120/commit/950c78076cd8c97eecfd569fa41c8f2f278c7751

**Comment by nickmadden** [comment]
When saving the variables to a file, we need to make sure and save the encrypted password as well as the salt. Also need to decide how we plan on saving the information.

**Comment by GQ722** [comment]
Nice work @nickmadden , I'm thinking our next step would include making a database and connecting to the database with the username and password provided. Let's not worry about drivers because I'm rusty on that part. Looking at the issue #3 and the commit 74ed4dc2c80880129db6335350cfabdcef092b1a developed by Team-3, we can get their help and kind of work together.

**Comment by Joshc5** [comment]
This issue was originally "Create Alias / Connections Window GUI" which is completed, along with the encryption implementation. We can start another issue for the database connections, and as well an issue for the saving of alias information securely. 
- Complete and Closed.
