### ISSUE TITLE
Implement cancel button in Preferences class

### ISSUE THREAD

**Issue by Bromveld** [rsanchez-wsu/sp16-ceg3120#104]
Figure out a way to close the tab when not saving changes to the preferences

**Comment by tyronv** [comment]
OK I tried this for almost a week and a half to no avail. We need to add a pseudo button on the tab label to get it to work . I tried modifying the code on the site below
https://docs.oracle.com/javase/tutorial/uiswing/components/tabbedpane.html which did not work.

**Comment by Bromveld** [comment]
Rolling to Milestone 6

**Comment by Bromveld** [comment]
For some reason the last commit with closes in the title did not close this issue, will try fixes next time
