### ISSUE TITLE
Create swing page for the Search History

### ISSUE THREAD

**Issue by Bromveld** [rsanchez-wsu/sp16-ceg3120#107]
Create a panel to display the search\query history in the Gui

**Comment by tyronv** [comment]
I created aworking swing SearchHistory swing window. However I was unable to push upstream due to errors while attempting to push. I will seek assistance with team members during my team meeting on Sunday 3/20/16

**Comment by meleno10** [comment]
I added Queries.java to the menu options in commit f4ff5dd (and then forgot to include the issue in the commit message). This should combine with Tyrone's new GUI easily

**Comment by meleno10** [comment]
Commit 8eac07a updated the GUI for Queries.java. The issue number was in the commit message but apparently it didn't post

**Comment by Bromveld** [comment]
We have finished this issue and will create a new one when we have the data to integrate.
