### ISSUE TITLE
Create a basic query builder backend

### ISSUE THREAD

**Issue by kenton-dover** [rsanchez-wsu/sp16-ceg3120#108]
Need this to be able to submit queries. Need to make classes extend an abstract class. Working on backend to the query builder GUI. 

This issue is for tracking the progress made on the underlying code which runs the Query Builder. We want to be able to suggest different queries which are commonly used, as well as correct syntax and offer code completion. These functions are diverse and complex and will require a lot of effort on our developers part to complete.

Initially, we simply want to be able to hit a couple buttons, and have each button insert code into the text field that is the Query Builder. The user will then be able to "fill in the blanks" for table names and conditions that vary from query to query.

**Comment by kenton-dover** [comment]
Reference commit  0885184 forgot to link it

"Fixed issues from updating code. Reimplemented the connect window
closing method. Created an abstract class and fixed the connectors
so they extend it. Started work on basic querybuilder."

**Comment by REDKAN** [comment]
I am working with Patrick to finishing up the CreateWindow connection to Derbyconnector.

**Comment by rsanchez-wsu** [comment]
@kenton-dover @REDKAN @sonicprime The description for this issue needs to be improved. Please make sure it describes the desired end state and completion criteria.

**Comment by bonnie-shields** [comment]
This is completed. We are able to type a Select statement and have it display the output. There will be new issues to work out any modifications or exceptions. Close #108
