### ISSUE TITLE
Display a database from Issue #80

### ISSUE THREAD

**Issue by alisonguyton** [rsanchez-wsu/sp16-ceg3120#110]
After connecting to a database on local machine through the embedded derby driver, that database from the .zip that closed issue #80 will be displayed using the GUI.

**Comment by alisonguyton** [comment]
Database from issue #80 does not meet the conditions to be a derby database. This issue is closed because it cannot be completed.

**Comment by rsanchez-wsu** [comment]
@alisonguyton FYI, the invalid label is more appropriate for this situation.
