### ISSUE TITLE
Add JMenuItem Icons

### ISSUE THREAD

**Issue by Joshc5** [rsanchez-wsu/sp16-ceg3120#118]
Add beautiful icons to all of the JMenuItems to make it looks super fancy and professional!

**Comment by Joshc5** [comment]
@GQ722 added icons for Open, Save, New, Welcome, About SQLizard.

commit f193145
commit 76009fb

**Comment by Joshc5** [comment]
I updated icons for New, Open, Save, and Welcome. I also added Save As option with an icon, Full Screen icon, Top icon, Bottom icon, and Find icon.

commit 4a9924668fd81c5682adf6cf3285a1df936eb72d
commit a0e73a6b8251b6611316465c8043edf4822353b6

**Comment by Joshc5** [comment]
Created README under img folder to list where all of our icons/images came from. Also updated a couple of the icons to ensure that we weren't violating any sort of copyright/licensing.

commit 02b4a893d1a7281bb10431eeffd34f76d8259537

**Comment by GQ722** [comment]
Added a new icon for 'Replace' JMenuItem. 
Updated README.txt file.

commit caa580e
