### ISSUE TITLE
Create Class to handle exption errors.

### ISSUE THREAD

**Issue by rtschock** [rsanchez-wsu/sp16-ceg3120#121]
Create a start of a new class to centrally locate the exceptions for programmers to reference too.

**Comment by rsanchez-wsu** [comment]
This is an excellent idea.  One additional thing to consider is that if we are doing to centralize exception handling, it makes it very easy to also log all exceptional conditions.  I recommend that logging be considered as part of the design and implementation of this new class.

**Comment by kenton-dover** [comment]
Todd made this commit, but forgot to include the issue in it. Commit id  0f7cf74

**Comment by rtschock** [comment]
Closing #121. I have created a new class that Extends from the Super Class. Will need a new issue created to populate with a switch statement.
