### ISSUE TITLE
Have listeners for all settings in Preferences

### ISSUE THREAD

**Issue by Bromveld** [rsanchez-wsu/sp16-ceg3120#126]

**Comment by rsanchez-wsu** [comment]
@Bromveld Please update the issue description so that it describes what defect needs to be fixed or what new feature needs to be implemented and also include clearly stated completion criteria.

**Comment by Bromveld** [comment]
We created action listeners for the check boxes and for the number of queries and default encoding combo boxes

We still need to get the Default views and list of databases for default database from teams working on those issues.
