### ISSUE TITLE
Create the "copy" edit toolbar option

### ISSUE THREAD

**Issue by ltlindon** [rsanchez-wsu/sp16-ceg3120#135]
Create functionality for the copy option in the edit tab  of the toolbar.
This will allow the user to copy a selected section of content. (will discuss where the copied content will go)

**Comment by Joshc5** [comment]
I have implemented the functionality for copying. It is currently commented out as we need the name of the query builder/code window from Team 3 first.

commit a565620d67e93ef91c81aaf58c4f1e5757766de3

**Comment by Joshc5** [comment]
I have fully implemented this. 

commit 4691ca8537033de31ea973924e0fe0e5f0f9563f
