### ISSUE TITLE
Create the "paste" edit toolbar option

### ISSUE THREAD

**Issue by ltlindon** [rsanchez-wsu/sp16-ceg3120#136]
Create functionality for the paste option in the edit tab of the toolbar.
This will allow the user to paste previously copied content into the location of the cursor.

**Comment by Joshc5** [comment]
I have implemented the functionality for pasting. It is currently commented out as we need the name of the query builder/code window from Team 3 first.

commit a565620d67e93ef91c81aaf58c4f1e5757766de3

**Comment by Joshc5** [comment]
I have fully implemented this. 

commit 4691ca8537033de31ea973924e0fe0e5f0f9563f
