### ISSUE TITLE
Create the "find and replace" search toolbar option

### ISSUE THREAD

**Issue by ltlindon** [rsanchez-wsu/sp16-ceg3120#144]
Create the functionality for the find and replace option in the search tab of the toolbar.
This will allow the user to write content, and then search through the currently selected window for any instance of this content, and then if desired they can then replace it with new specified content.

**Comment by Joshc5** [comment]
@GQ722 Almost has this find/replace fully functional. It just need to show the highlighted text on Finds, and 1 other bug I believe so. Also needs to be connected to Team 3's SQL builder/code window once we merge with them.

Note: I can't find the commit to reference here as I believe it was under Team 5-Dev which is now deleted.

**Comment by ltlindon** [comment]
above commit finished this issue
