### ISSUE TITLE
Create the "open file" file toolbar option

### ISSUE THREAD

**Issue by ltlindon** [rsanchez-wsu/sp16-ceg3120#148]
Create the functionality for the open file option in the file tab of the toolbar.
This will allow the user to open a file in a new window of the program GUI.

**Comment by Joshc5** [comment]
Open file functionality is somewhat done. Once we merge with Team 3 to get their SQL builder/code window, it can be implemented the rest of the way.

Note: I can't find the commit to reference here as I believe it was under Team 5-Dev which is now deleted.
