### ISSUE TITLE
Create the "save file" file toolbar option

### ISSUE THREAD

**Issue by ltlindon** [rsanchez-wsu/sp16-ceg3120#149]
Create the functionality for the save file option in the file tab of the toolbar.
This will allow the user to save the contents of the currently selected window.

**Comment by Joshc5** [comment]
Save File was already partially implemented by @GQ722. Once we merge with Team 3 to get their SQL builder/code window, it can be implemented the rest of the way. 

Note: I can't find the commit to reference here as I believe it was under Team 5-Dev which is now deleted.
