### ISSUE TITLE
Display error messages and finish autofill password function in CreateWindow

### ISSUE THREAD

**Issue by Joshc5** [rsanchez-wsu/sp16-ceg3120#17]
Silent C4: Information has been written to a binary file, and a write function has been made for future use. Some error messages still need displaying and an else statement for when a user doesn't want to save a password.

**Comment by ltlindon** [comment]
When I get home I will clean up the password function, we don't need an else statement, and somewhere in the if we need to make code that pastes the password into the log in password text field, which also means we need to make a basic log in GUI for after you create the alias, when you just want to log in, unless someone else has a different way they want to do it.

**Comment by Joshc5** [comment]
I added statements to require users to input all the information when connecting, and also added statements that requires the user to at least enter Alias Name, Database URL, and Username when saving an alias.

**Comment by rsanchez-wsu** [comment]
Before this issue can be considered closed, please incorporate the changes I described in my comment on commit 066f2a5.

**Comment by Joshc5** [comment]
This is complete.

-Closing.
