### ISSUE TITLE
Implement autocomplete for the querybuilder input

### ISSUE THREAD

**Issue by kenton-dover** [rsanchez-wsu/sp16-ceg3120#181]
Create the implementation

**Comment by sirelewop14** [comment]
Here is some code to test with this feature
`select * from inventory;
insert into inventory values(12,'SUPERCOOKIES','cookies','cookies',4,5.00,50);
insert into inventory values(13,'Mantecados','','Pastry',4,5.00,50);
insert into inventory values(14,'Spanish Flan','cookies','cookies',4,5.00,50);
insert into inventory values(15,'Polvorones','cookies','cookies',4,5.00,50);
insert into inventory values(15,'Churros','t-t-t-tasty, tasty','cookies',4,5.00,50);
insert into inventory values(16,'Churros','t-t-t-tasty, tasty','cookies',4,5.00,50),(17,'Churros','t-t-t-tasty, tasty','cookies',4,5.00,50);`

**Comment by kenton-dover** [comment]
This should have been closed after class last wednesday
