### ISSUE TITLE
Build internal DTD decleration

### ISSUE THREAD

**Issue by mspehar** [rsanchez-wsu/sp16-ceg3120#19]
Create the DTD that will be declared inside the XML file

**Comment by mspehar** [comment]
Completed and closed #19

**Comment by rsanchez-wsu** [comment]
@mspehar Please associate the commit that fixes this issue with the issue.  You can do that by mentioning it in a comment on this issue if the commit has already been pushed.  When you do that, also remember to change the state label of this issue to state-done.

**Comment by mspehar** [comment]
Pushed to Team 1 Dev Site Closed #19
