### ISSUE TITLE
Create Database

### ISSUE THREAD

**Issue by kenton-dover** [rsanchez-wsu/sp16-ceg3120#2]
Use the created sql script to create the database server. With logons.

**Comment by REDKAN** [comment]
hi

**Comment by sirelewop14** [comment]
Created the MySQL database for testing and provisioned user accounts for our team. All credentials and connection information were securely and privately disclosed to the appropriate users. This allows us to have a common database to test our builds and connections against. 

This closes issue #2.

**Comment by rsanchez-wsu** [comment]
@sirelewop14 If this ticket has really been closed, please make sure to set its state label to done.
