### ISSUE TITLE
Create a basic connection to a database

### ISSUE THREAD

**Issue by GashMcNash** [rsanchez-wsu/sp16-ceg3120#20]
To show the most minimum functionality, we must implement jdbc to connect to a database. This can be done just by creating a basic connection class and getting a connection class to a DB that is either local or hosted elsewhere.

**Comment by rsanchez-wsu** [comment]
Please change the description of this issue.  The current description "Create a basic connection to a database" would be a good title.  The issue description should include what needs to be done and what the completion criteria would be.

**Comment by rsanchez-wsu** [comment]
@CHeritage Can you describe what changes were made that constitute a closure of this issue, or better yet mention the specific commits.

**Comment by alisonguyton** [comment]
Connection successfully created on Team-6 origin branch
