### ISSUE TITLE
Create Splash Screen with Loading Bar

### ISSUE THREAD

**Issue by codybutz** [rsanchez-wsu/sp16-ceg3120#21]
![sqlizard](https://cloud.githubusercontent.com/assets/10050505/13062224/fdcf0e68-d40a-11e5-9981-850a03291f8c.jpg)

Create a Java Swing SplashScreen with a loading bar.

**Comment by AlexVance** [comment]
Added splash screen to build via commit: 8fbb835, this closes Issue #21.
