### ISSUE TITLE
Create Base GUI based on Mockups

### ISSUE THREAD

**Issue by codybutz** [rsanchez-wsu/sp16-ceg3120#22]
<img width="919" alt="screen shot 2016-02-03 at 10 16 18 pm" src="https://cloud.githubusercontent.com/assets/3670430/12804762/c98125f6-cac3-11e5-9acb-cac96e63ff78.png">

Build out the mockup using Java Swing. This Base GUI will assist the applications functionality. After loading the Splash screen, the BaseGUI should determine what page should be opened.

Needs to be determined:
- The menu items for "File"
- The menu items for "Edit"
- The menu items for "Window"
- The menu items for "Help"

**Comment by rsanchez-wsu** [comment]
@codybutz Please don't forget to place this issue under your team's milestone.

**Comment by codybutz** [comment]
@rsanchez-wsu Done.

**Comment by codybutz** [comment]
The following commits regard this issue:

commit 074578 - Removed useless comment.

commit 6ee941 - Created a tab pane to hold all the tabs within the application. Created a sample start page tab that has nothing in it.... YET. Fixed some comments that were just me being lazy.

commit 1d5c9e - Added fullscreen to Base Gui Window menu. Also included Cut, Copy, and Paste in Edit Menu.

commit a25e14 - Removed System.exit() from MainGui to satisfy errors from FindBugs. System.exit() destroys the whole Virtual Machine which can harm the application.

I will put the issue number in the commit from now on.

**Comment by codybutz** [comment]
The BaseGUI has been finished and our team is moving on to building out the separate components.
