### ISSUE TITLE
Xml Write class created 

### ISSUE THREAD

**Issue by tyronv** [rsanchez-wsu/sp16-ceg3120#28]
I have created and pushed xmlWrite class which has a few issues that I will need assistance with fixing.

**Comment by meleno10** [comment]
I fixed all errors and the build is not broken, but there's some issues in the code you should look at. I added comments where necessary about it
Commit: eeb503c

**Comment by Bromveld** [comment]
We created this and posted it to our Team 1 branch. We were able to fix some errors, and commented out the rest that were causing a broken build
