### ISSUE TITLE
Create basic login script for testing

### ISSUE THREAD

**Issue by sirelewop14** [rsanchez-wsu/sp16-ceg3120#3]
Need to get familiar with JDBC drivers and java code to connect to a database. Will create a simple login script to test connections to our teams test MySQL server. This script will be a rough outline of what our first Milestone should look like.

We want to ask for server address and credentials. Eventually the user should be able to select the driver/type of server to connect to. For now we will just run with the appropriate MySQL driver.

**Comment by sirelewop14** [comment]
This issue has been resolved by the following commit.

579a9962c80d687f1156024ee1f1c527775ad8c4

**Comment by rsanchez-wsu** [comment]
@sirelewop14 If this ticket has really been closed, please make sure to set its state label to done.
