### ISSUE TITLE
Integrating XML in read and write code with Profile page

### ISSUE THREAD

**Issue by Bromveld** [rsanchez-wsu/sp16-ceg3120#37]
integrating our various code and making it show up on the profile page

**Comment by Bromveld** [comment]
Rolled this issue to Milestone 3

**Comment by meleno10** [comment]
Fixed more checkstyle errors in commit 358eca4

**Comment by joshuastevenson** [comment]
#125 Supersedes this. Settings are now handled with JavaBean XML[de/en]coder
