### ISSUE TITLE
Implement a database view

### ISSUE THREAD

**Issue by alisonguyton** [rsanchez-wsu/sp16-ceg3120#39]
Need database. Working on getting a host for a Derby database. Until then this can be started. Use demoDB as reference. Do not worry about GUI yet, use console output?

**Comment by rsanchez-wsu** [comment]
A host is not required for Derby.  While Derby can run in networked mode, I had intended that we use it in embedded mode.  In that mode, you simply pass it a connection string that points to a location on disk and then once it has connected you can interact with the on-disk database in the same way you would interact with any networked database.  You can prepare and execute statements using the same JDBC mechanisms as with other databases.

**Comment by alisonguyton** [comment]
New Issue was created..

**Comment by rsanchez-wsu** [comment]
@alisonguyton Which issue?  Remember to mention new related issues in a comment when closing old issues to preserve continuity.
