### ISSUE TITLE
Create GUI Mockup for splashscreen, add and view driver pages

### ISSUE THREAD

**Issue by AlexVance** [rsanchez-wsu/sp16-ceg3120#4]
Need to create mockup pages for a splashscreen and add/view driver page.

Splashscreen:
![splashscreen_pic](https://cloud.githubusercontent.com/assets/10050505/12795742/6f5571ac-ca89-11e5-9879-23ffd8474a3d.png)

Driver Page:
![driver_page](https://cloud.githubusercontent.com/assets/10050505/12795746/7466d97e-ca89-11e5-9925-6c26d165fffd.png)

**Comment by codybutz** [comment]
Created four new Mockups for the application.

1.) Connection - This screen will be the initial screen that the user will see when they open up a new connection. This screen will have tabs that link to pages such as: Content, Structure, Relations, Query Builder, ER Diagram, Backup/Restore Database.

2.) Content - Pulls up to 1000 rows of table data from the live server into a Results table, and enables editing. Data can be saved directly to the live server.

3.) Structure - Lists the columns in the table.

4.) Relationships - Lists the relationships in the table.

**Comment by rsanchez-wsu** [comment]
@AlexVance @codybutz Please make sure to set a priority for this issue.

**Comment by AlexVance** [comment]
Finished add/view driver page mock up and splash screen mock up. This resolves Issue 4.

**Comment by rsanchez-wsu** [comment]
@AlexVance @codybutz Please add links to this issue so that readers can see the mockups.

**Comment by AlexVance** [comment]
Issue complete. Final mock up pages: http://imgur.com/a/FCXRp

This resolves issue 4.

**Comment by rsanchez-wsu** [comment]
@AlexVance I looked at the link, but there only appears to be mock ups for the connection window and the splash screen.  Please make sure that all the mock ups are available.  Also, please upload the images directly to this issue and to the project wiki.

**Comment by AlexVance** [comment]
The first page is both Add/View driver in a combined page, and then the splash screen. That's what we were planning on to show the class, I hope that's okay. I am uploading them in the issue now

**Comment by rsanchez-wsu** [comment]
@AlexVance Thanks.  I just want to make sure that everything related to an issue is actually captured within the issue.  As far as uploading to the issue, you can just drag and drop the files into the comment box and it should do the right thing.

**Comment by AlexVance** [comment]
Added the pictures to the top comment, they are completed. This closes issue 4.

**Comment by rsanchez-wsu** [comment]
@AlexVance Thanks!
