### ISSUE TITLE
GUI for database viewing, select statements, and queries 

### ISSUE THREAD

**Issue by alisonguyton** [rsanchez-wsu/sp16-ceg3120#41]
Work with team 3's mock up.

**Comment by rsanchez-wsu** [comment]
This issue should probably have a more verbose description and include links to the referenced mock ups.

**Comment by CHeritage** [comment]
Link to the GUI mockup: https://github.com/rsanchez-wsu/sp16-ceg3120/wiki/Query-Builder

**Comment by alisonguyton** [comment]
not sure if a commit was made to close this issue, but this is is being worked on continuously and various issues have been created that are more specific, so this issue is no longer relevant.
