### ISSUE TITLE
Update SQL Classes to have generic SQL execution methods

### ISSUE THREAD

**Issue by sirelewop14** [rsanchez-wsu/sp16-ceg3120#42]
Need to create some methods in the SQL classes that receive strings of SQL statements, prepare them, execute them, and return the results as a string.

**Comment by sirelewop14** [comment]
I have tested the MySQL code, and found it works. We still need to nail down exactly what format the output is coming in: break up line by line, or return one big string and split it up after processing.

PostgreSQL still needs some debugging.

**Comment by sirelewop14** [comment]
This has been completed. Closing issue.

**Comment by rsanchez-wsu** [comment]
@sirelewop14 Please don't forget about changing the state tag in the future.
