### ISSUE TITLE
Alias Password Read & Validate XML Files

### ISSUE THREAD

**Issue by nickmadden** [rsanchez-wsu/sp16-ceg3120#45]
We need to change the reading and writing of aliases to read and write to xml files instead of text files.

**Comment by rsanchez-wsu** [comment]
@nickmadden Don't forget about DTD validation, like what Team 1 is doing with issue #47.  You can either do that as part of this issue, or create a separate issue.  In any event, you will want to make sure and minimize duplication of effort.

**Comment by nickmadden** [comment]
Forgot to tag this issue with my last commit: d783125864c986aa0f91ba282b2d1b031e492c40
The password encryption read/write was fixed in this commit.
