### ISSUE TITLE
Add database option iteration

### ISSUE THREAD

**Issue by mjohnson6166** [rsanchez-wsu/sp16-ceg3120#57]
Add iteration that allows user to continue adding, deleting, or etc. items to the table. Currently only one option can be chosen before the program ends.

**Comment by rsanchez-wsu** [comment]
@davidPanson @mjohnson6166 Please add a comment that reference the specific git commit(s) that resolved this issue or a comment that describes with some detail in what way this has been resolved.

**Comment by davidPanson** [comment]
ref #63 also added iteration to the program.
