### ISSUE TITLE
Create "file" toolbar options.

### ISSUE THREAD

**Issue by ltlindon** [rsanchez-wsu/sp16-ceg3120#64]
Options such as open file, save file, print file, and others deemed necessary.

**Comment by Joshc5** [comment]
GUI/drop-down menus complete for this. commit 331e63b1830f89159348eb8c5fa5327b00463f53

**Comment by Joshc5** [comment]
I added (started) the functionality for File < Open. Right now it just utilizes JFileChooser, and then prints out what file you chose. Once we get the SQL code window from Team 3, then we can actually start reading/writing files. 

commit bc886336823478ac6cd3ea8a4a69cc63d2b8b091

**Comment by rsanchez-wsu** [comment]
@ltlindon @Joshc5 Please don't forget that this issue needs a state label.

**Comment by Joshc5** [comment]
@GQ722 started the functionality for File < Save using JFileChooser. We still need a code window from the other team before we can fully complete this (write to file).

commit f1931455642a0b119dc9e78cf5392a66e8c8e538

**Comment by ltlindon** [comment]
finished GUI for file toolbar options
