### ISSUE TITLE
Create "connections" toolbar options

### ISSUE THREAD

**Issue by ltlindon** [rsanchez-wsu/sp16-ceg3120#65]
Options such as new connection, disconnect from "......", disconnect from all,  new driver, and others deemed necessary.

**Comment by Joshc5** [comment]
GUI/drop-down menus complete for this. commit 331e63b1830f89159348eb8c5fa5327b00463f53

Still need to make these functional.

**Comment by GQ722** [comment]
Update: 
1. GUI implementation is added for 'Connect to Database' JMenuItem under 'Session' JMenu 
Commit: 1cfcad1e0aaf48a6f4b22701799955a76d8a1668

**Comment by Joshc5** [comment]
I removed the Create Alias menu option as it is not needed.

commit ce742cd809fb7a4aaf9e0670704238ccc4060826

**Comment by rsanchez-wsu** [comment]
@ltlindon @Joshc5 Please don't forget that this issue needs a state label.

**Comment by ltlindon** [comment]
finished GUI for connections toolbar options
