### ISSUE TITLE
Create "search" toolbar options

### ISSUE THREAD

**Issue by ltlindon** [rsanchez-wsu/sp16-ceg3120#67]
Options such as top of page, bottom of page, go to line ".....", find and replace, and others deemed necessary.

**Comment by Joshc5** [comment]
GUI/drop-down menus complete for this. commit 331e63b1830f89159348eb8c5fa5327b00463f53

**Comment by rsanchez-wsu** [comment]
@ltlindon @Joshc5 Please don't forget that this issue needs a state label.

**Comment by GQ722** [comment]
Added a GUI for 'Find' and 'Replace' JMenuItems.

commit f108d17 and caa580e

**Comment by ltlindon** [comment]
finished GUI for the search toolbar options
