### ISSUE TITLE
Create "window" toolbar options

### ISSUE THREAD

**Issue by ltlindon** [rsanchez-wsu/sp16-ceg3120#68]
Options such as zoom in, zoom out, full screen, windowed view, and others deemed necessary.

**Comment by Joshc5** [comment]
GUI/drop-down menus complete for this. commit 331e63b1830f89159348eb8c5fa5327b00463f53

**Comment by rsanchez-wsu** [comment]
@ltlindon @Joshc5 Please don't forget that this issue needs a state label.

**Comment by ltlindon** [comment]
Finished the GUI for the window toolbar options
