### ISSUE TITLE
Create "edit" toolbar options

### ISSUE THREAD

**Issue by ltlindon** [rsanchez-wsu/sp16-ceg3120#69]
Options such as undo, redo, select all, select line "......", cut, copy, paste.

**Comment by Joshc5** [comment]
GUI/drop-down menus complete for this. commit 331e63b1830f89159348eb8c5fa5327b00463f53

**Comment by rsanchez-wsu** [comment]
@ltlindon @Joshc5 Please don't forget that this issue needs a state label.

**Comment by ltlindon** [comment]
Finished GUI for edit toolbar options
