### ISSUE TITLE
Create XML for recent queries

### ISSUE THREAD

**Issue by meleno10** [rsanchez-wsu/sp16-ceg3120#72]
I was thinking this could be something like 
<query1> </query1>
<query2> </query2>
for each of the 4 enum values we are using (Zero, Five, Ten, Twenty). We can implement the other easter egg values later.
I was picturing this as 4 separate pages that we could call based on the selected menu option

**Comment by rsanchez-wsu** [comment]
@meleno10 Your XML got lost.  It showed up in the slack channel, but it isn't here in the issue write up.  This is what you meant (I was able to get it to show up here by formatting it as code):

```
<query1> </query1>
<query2> </query2>
```

Also, I don't think using tag names like query1 is a good idea.  Better would be something like this:

```
<query num="1"> </query>
<query num="2"> </query>
```

**Comment by rsanchez-wsu** [comment]
@meleno10 Your commit that closed this wasn't adequate.  I've made some comments on that commit.  Please fix the problems and then commit again to close this issue.
