### ISSUE TITLE
finalize derby driver

### ISSUE THREAD

**Issue by sonicprime** [rsanchez-wsu/sp16-ceg3120#73]
the out most shell of the driver is created but improve it to  a better working version

**Comment by REDKAN** [comment]
I started to work with him yeah~.

**Comment by REDKAN** [comment]
As far we can tell that we are matched up with the MySQL connect driver. Therefore, after meeting, we are likely to close this issue within a day or so.

**Comment by REDKAN** [comment]
Close the  issue #73  60ae1dc

**Comment by rsanchez-wsu** [comment]
@REDKAN Please don't forget to change the state label when closing an issue.
