### ISSUE TITLE
Create a basic GUI for the query builder

### ISSUE THREAD

**Issue by bonnie-shields** [rsanchez-wsu/sp16-ceg3120#74]
This issue will create a basic GUI for the query builder. It should pop open a window for now with a text box to input SQL statements and a Go button to run the script.

**Comment by sirelewop14** [comment]
Moving to new Milestone.

**Comment by bonnie-shields** [comment]
Basic GUI created for Query Builder. Will implement Tabbed Pane in a new issue.
