### ISSUE TITLE
Create a embedded derby database (generic) to use as a testing source

### ISSUE THREAD

**Issue by alisonguyton** [rsanchez-wsu/sp16-ceg3120#80]
We need a zip file uploaded to slack for the team to download in order to begin testing of the GUI and User Select statements.

**Comment by jcabonce** [comment]
[employee_db.zip](https://github.com/rsanchez-wsu/sp16-ceg3120/files/165944/employee_db.zip)

This is a generic employee database with basic information such as name, birthday, first and last name
