### ISSUE TITLE
In user profile, verticleGridLines should be verticalGridLines

### ISSUE THREAD

**Issue by rsanchez-wsu** [rsanchez-wsu/sp16-ceg3120#87]
In `Profile.xml`, `profile.dtd`, and `TemplateProfile.xml`, the element `verticleGridLines` should really be `verticalGridLines`.  The former is clearly misspelled.

**Comment by meleno10** [comment]
I apologize for not knowing how to spell....I'm pretty sure those are my errors. I'll take care of it.

**Comment by meleno10** [comment]
Closed with commit 5bbf35e
