### ISSUE TITLE
Should we rename profile.dtd to Profile.dtd?

### ISSUE THREAD

**Issue by meleno10** [rsanchez-wsu/sp16-ceg3120#89]
This would match the casing in our XML files (and most if not all others)

**Comment by meleno10** [comment]
We have decided to rename it to Preferences.dtd

**Comment by rsanchez-wsu** [comment]
@meleno10 Was there a code change associated with closing this ticket?  If so, please add a comment referencing the applicable commit(s).  If there was no code change, lease describe in a bit more detail why the issue is now considered closed.
