### ISSUE TITLE
Merge branch back to Team 3 - Dev

### ISSUE THREAD

**Issue by bonnie-shields** [rsanchez-wsu/sp16-ceg3120#90]
Need to merge team 3 team 5 dev back to team 3 dev since we are no longer collaborating with team 5

**Comment by bonnie-shields** [comment]
Merge successful on 2/25/2016

**Comment by rsanchez-wsu** [comment]
@bshield14 Please add a comment to this issue with the commit ID of the merge commit.

**Comment by bonnie-shields** [comment]
https://github.com/rsanchez-wsu/sp16-ceg3120/commit/5763754066f7c1387035430fb7bf31fba755bc7a
