### ISSUE TITLE
Merge Team 2 and Team 3

### ISSUE THREAD

**Issue by sirelewop14** [rsanchez-wsu/sp16-ceg3120#91]
Need to merge these branches to further GUI integration.

**Comment by sirelewop14** [comment]
I merged the branches and committed to a new dev branch for building the integrated code. Forgot to add the issue # in the commit. The commit ID is e11b1ceeba8cdc434ea04f09903d979a169fcc43

**Comment by sirelewop14** [comment]
This branch is dead, we will move onto better code that is further along. Closing issue

**Comment by rsanchez-wsu** [comment]
@sirelewop14 If one of the branches is now considered dead and it has been fully merged into another branch, please remove the dead branch from GIt.  You will also need to remove it on the remote (you can consult the Pro Git book or Google for documentation on how to do that).  Also, please update the state of this ticket to reflect that it is in fact done.

**Comment by sirelewop14** [comment]
I am going to take @rsanchez-wsu advice and clean up the other branches our team has created. I will delete the expired Dev collaboration branches and leave our team with 2 branches total. Stable build, and Dev Build. I will also merge our current build into stable so that we have a reference point.
