### ISSUE TITLE
Move menu and other window elements to MainApp

### ISSUE THREAD

**Issue by Bromveld** [rsanchez-wsu/sp16-ceg3120#92]
Also, make Profile a stand alone pane. Work on getting cancel button to close it or add a close tab button.

**Comment by Bromveld** [comment]
I am closing this issue for Milestone 4 and opening a new issue for the cancel button and another for the multiple preferences tab in milestone 5

**Comment by rsanchez-wsu** [comment]
@Bromveld To preserve continuity, please add a comment that gives a link to the new issue that was created.

**Comment by Bromveld** [comment]
Cancel button issue [#104]
[](https://github.com/rsanchez-wsu/sp16-ceg3120/issues/104)

multiple preferences issue #105 
[](https://github.com/rsanchez-wsu/sp16-ceg3120/issues/105)

**Comment by rsanchez-wsu** [comment]
@Bromveld thanks!
